Blockshape
FrancescAlted/caterva pull request #36
Opened 2020-04-17 12:03 UTC by oscargm98

Update to a new version of Caterva that takes care of blocks (subpartitions).
test_repart_chunk works correctly, but there are some bugs in test_get_slice_buffer that need to be fixed to evaluate the performance of test_append and itself.

2020-04-23 08:29 UTC, aleixalcacer requested changes

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.c
> -    (*array)->empty = false;
This cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.c
> +            case CATERVA_STORAGE_BLOSC:caterva_blosc_array_free(ctx, array);
A space or a line break is missing.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.c
> +            case CATERVA_STORAGE_PLAINBUFFER:caterva_plainbuffer_array_free(ctx, array);
A space or a line break is missing.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.c
> -    (*array)->filled = true;
This cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.c
> -    (*array)->empty = false;
This cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
> +#define CATERVA_MAXDIM 8
Change the name to `CATERVA_MAX_DIM`.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
> -#define CATERVA_MAX_METALAYERS BLOSC2_MAX_METALAYERS - 1
This cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
>  static const caterva_config_t CATERVA_CONFIG_DEFAULTS = {
Incorrect indentation.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
> +            CATERVA_STORAGE_PLAINBUFFER,
Incorrect indentation.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
> -}caterva_metalayer_t;
This struct cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
> -    caterva_metalayer_t metalayers[CATERVA_MAX_METALAYERS];
This cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
> -    int32_t nmetalayers;
This cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
> +int caterva_blosc_array_repart_chunk(int8_t *repartedchunk, int repartedchunksize, void *chunk, int chunksize, caterva_array_t *array);
Context has to be added at the beginning. The type of both chunks has to be `void` (You can cast them inside to `uint8_t`).
Suggestion: rename `repartedchunk` to `rchunk`?

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva_blosc.c
> -        if ((*array)->sc->frame != NULL) {
This cannot be removed.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva_blosc.c
> +    if (repartedchunksize != array->extendedchunksize * array->itemsize) {
Use existing caterva errors (`CATERVA_ERROR_?`) or define a new one.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva_blosc.c
> +    if (chunksize != array->chunksize * array->itemsize) {
Use existing caterva errors (CATERVA_ERROR_?) or define a new one.

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva.h
>  typedef struct {
Suggestion: change `extended-` prefix to `ext-`? (`extendedchunksize` to `extchunksize`?

2020-04-23 08:29 UTC, aleix11alcacer commented on caterva/caterva_blosc.c
> -    // Serialize the dimension info in the associated frame
This block of code is the correct one.

2020-04-24 15:31 UTC, FrancescAlted commented on caterva/caterva.h
>  typedef struct {
So as to avoid too long names, how about `ext_chunksize` that at least gives some sense of two-word name?

2020-05-11 10:34 UTC, aleixalcacer commented on caterva/caterva.c
> +            if (chunksize != array->next_chunksize * array->itemsize) {
why did you move it inside?

2020-05-11 10:34 UTC, aleix11alcacer commented on CMakeLists.txt
> +# cmake_policy(SET CMP0077 NEW)
Uncomment

2020-05-11 10:34 UTC, aleix11alcacer commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5.1)
Change VERSION to 3.12

2020-05-11 10:34 UTC, aleix11alcacer commented on caterva/caterva_blosc.c
> +    aux2[7] = d_epshape[7] / d_spshape[7];
Why aux2?

2020-05-11 11:48 UTC, oscargm98 commented on caterva/caterva.c
> +            if (chunksize != array->next_chunksize * array->itemsize) {
there was necessary to differenciate both cases

2020-05-11 11:52 UTC, oscargm98 commented on caterva/caterva.h
>  static const caterva_config_t CATERVA_CONFIG_DEFAULTS = {
??

2020-05-11 11:54 UTC, oscargm98 commented on caterva/caterva.h
> +            CATERVA_STORAGE_PLAINBUFFER,
it must be 4 spaces, isn't it?

2020-05-11 11:56 UTC, oscargm98 commented on caterva/caterva.h
>  typedef struct {
ext_chunksize then?

2020-05-11 12:07 UTC, oscargm98 commented on caterva/caterva_blosc.c
> +    aux2[7] = d_epshape[7] / d_spshape[7];
changed to aux

2020-05-11 12:12 UTC, oscargm98 commented on caterva/caterva_blosc.c
> -    // Serialize the dimension info in the associated frame
block added, but line 1173 is ok? (" if (storage->properties.blosc.filename != NULL) { ")

2020-05-15 10:29 UTC, aleixalcacer approved these changes

2020-05-15 10:34 UTC, merged

2020-05-15 10:51 UTC, FrancescAlted commented
Glad to see this finally merged.  Hats off to you guys!