Update documentation
FrancescAlted/caterva pull request #44
Opened 2020-07-17 11:54 UTC by aleix11alcacer

2020-07-27 10:37 UTC, FrancescAlted requested changes

2020-07-27 10:37 UTC, FrancescAlted commented on docs/sphinx/conf.py
> +copyright = '2020, Blosc Developers'
You need to keep expressing that copyright starts in 2019.  So 2019-2020 is correct here.

2020-07-27 10:37 UTC, FrancescAlted commented on docs/sphinx/getting-started/description.rst
> +Like other libraries like zarr, hdf5 or TileDB, Caterva stores the data into
HDF5 is normally written in upper case.

2020-07-27 10:37 UTC, FrancescAlted commented on docs/sphinx/getting-started/description.rst
> +These partition levels, that emulate the memory hierarchy of modern computers,
I am not sure that partition levels emulate cache hierarchy of computers.  As this is complex point, I suggest to just say that allow to access data efficiently with a larger set of data access patterns.

2020-07-27 10:37 UTC, FrancescAlted commented on docs/sphinx/getting-started/description.rst
> +types, geo-spatial...
I suppose this is also repeated in README.md.  I am wondering whether it is feasible to centralize this description somewhere and include from here.  Not extremely important, but planning for a single source of prose is always a good thing.

2020-07-27 11:24 UTC, aleix11alcacer commented on docs/sphinx/conf.py
> +copyright = '2020, Blosc Developers'
Fixed

2020-07-27 11:26 UTC, aleix11alcacer commented on docs/sphinx/getting-started/description.rst
> +These partition levels, that emulate the memory hierarchy of modern computers,
Fixed

2020-07-27 11:27 UTC, aleix11alcacer commented on docs/sphinx/getting-started/description.rst
> +Like other libraries like zarr, hdf5 or TileDB, Caterva stores the data into
Fixed

2020-07-27 11:30 UTC, aleix11alcacer commented on docs/sphinx/getting-started/description.rst
> +types, geo-spatial...
In README.md there is only a brief description of Caterva and a link to the documentation. So there should be no duplicate text. 

Make sense?

2020-07-27 11:50 UTC, FrancescAlted commented on docs/sphinx/getting-started/description.rst
> +types, geo-spatial...
Yes, it does.

2020-07-28 08:34 UTC, FrancescAlted approved these changes

2020-07-28 09:14 UTC, merged