Use cpplint
FrancescAlted/caterva pull request #48
Opened 2020-08-11 08:20 UTC by aleix11alcacer

2020-08-29 11:51 UTC, FrancescAlted requested changes
I like this one!  Please address the suggestions that I made and let's merge as soon as possible.

2020-08-29 11:51 UTC, FrancescAlted commented on caterva/caterva.h
> +#define CATERVA_CATERVA_H_
Too much redundancy in `CATERVA_CATERVA` prefix?

2020-08-29 11:51 UTC, FrancescAlted commented on caterva/caterva.h
> +#define CATERVA_VERSION_RELEASE 1 - dev /* for tweaks, bug-fixes, or development */
Are the additional blanks in `1 - dev` intended?

2020-08-29 11:51 UTC, FrancescAlted commented on caterva/caterva.h
> +                                                         .pparams = NULL};
I don't see why the new format for `caterva_config_t` is better than the previous one.

2020-08-31 10:28 UTC, aleix11alcacer commented on caterva/caterva.h
> +#define CATERVA_CATERVA_H_
It is determined by cpplint. If it is changed to `CATERVA_H_`, then:
```
caterva/caterva.h:19:  #ifndef header guard has wrong style, please use: CATERVA_CATERVA_H_  [build/header_guard] [5]
caterva/caterva.h:494:  #endif line should be "#endif  // CATERVA_CATERVA_H_"  [build/header_guard] [5]
```

2020-08-31 10:31 UTC, aleix11alcacer commented on caterva/caterva.h
> +#define CATERVA_VERSION_RELEASE 1 - dev /* for tweaks, bug-fixes, or development */
Fixed :)

2020-08-31 10:40 UTC, aleix11alcacer commented on caterva/caterva.h
> +                                                         .pparams = NULL};
To adapt Caterva to cpplint requirements, `clang-format` is used:

```
clang-format -style=file -i caterva/* 
```

And it changes it automatically. What do you think about using this workflow?

2020-09-08 10:15 UTC, merged