Caterva_meta_print
FrancescAlted/caterva pull request #93
Opened 2021-12-13 19:15 UTC by oscargm98

Add new function "caterva_meta_print" to Caterva

2021-12-14 09:38 UTC, aleixalcacer commented
I think we should not introduce this new feature (as is) for the following reasons:

1. The API `caterva_meta_*` is meant for all existing metalayers. However, `caterva_meta_print` will only work with the Caterva metalayer.
2. The API `caterva_meta_*` requires a pointer to a Caterva array. However, `caterva_meta_print` will only work with persistent arrays.

For this reasons, I'm going to propose an alternative:

```
int caterva_print_meta_info(caterva_ctx_t *ctx, caterva_array_t *array) {
    ...
}
```

Thus, if you want to print the info of a persistent array, you just need to open the array before calling this function.

What dou you think @FrancescAlted ?

Apart from this, could you (@oscargm98) give an example of what the output would look like?

2021-12-14 09:49 UTC, FrancescAlted commented
Yes, the idea was to have a utility for printing the metalayer info for existing Caterva frames.  But I agree that @aleixalcacer proposal adds more flexibility, so +1 to it.  Also, I am not a huge fan of long names, so I'd propose `caterva_print_meta()` instead.

2021-12-15 17:50 UTC, oscargm98 commented
Requested changes done! You can see the result running example_frame_generator, which will have even more examples when its PR is merged

2021-12-23 16:50 UTC, FrancescAlted requested changes

2021-12-23 16:50 UTC, FrancescAlted commented on examples/example_print_meta.c
> +int main() {
You may want to add a caterva file as a parameter so as to print meta info for it.

2021-12-23 18:41 UTC, oscargm98 commented on examples/example_print_meta.c
> +int main() {
Done!

2021-12-23 19:41 UTC, FrancescAlted approved these changes
LGTM.  Just fix my comment, and you can merge it.

2021-12-23 19:41 UTC, FrancescAlted commented on examples/example_print_meta.c
> + * $ <urlpath>
You rather mean `$ ./example_print_meta <urlpath1> <urlpath2>...` ?

2021-12-24 12:34 UTC, merged

2021-12-24 12:50 UTC, FrancescAlted commented on examples/example_print_meta.c
> + * $ <urlpath>
Fixed in afc5a79